### ISSUE TITLE
Module myNotebook not found

### ISSUE THREAD

**Issue by clabinsky** [keybuk/EDMC-Inara#1]
Hi --
I really like the idea of this plugin, but I cannot get it to work since module myNotebook is unknown. 

see line 38: import myNotebook as nb

Any help appreciated.

Thx,
cal

**Comment by keybuk** [comment]
The 'myNotebook' module is part of EDMC, I don't know why that wouldn't be in your PYTHON_PATH?

What happens when you start EMDC with this plugin in the correct location?

**Comment by clabinsky** [comment]
EDMC starts like normal, but there is no config option for inara nor does it update my inara account.

so i just tried to run the plugin using python's IDLE to get a clue what goes wrong, but my python environment obviously doesn't even know about EDMC and its library stuff. Thus my approach leads to nothing.

Don't know why your plugin doesn't work though. 

Here is a screenshot of my EDMC: 
![screenshot_1](https://cloud.githubusercontent.com/assets/12901677/21597690/006ce6ee-d14f-11e6-85ea-0095edb55c17.png)

**Comment by keybuk** [comment]
Do you have the log from EDMC?

**Comment by clabinsky** [comment]
where do i find the log file? couldn't find it in my appdata nor in the
program folder...

Am 03.01.2017 um 19:59 schrieb Scott James Remnant:
> Do you have the log from EDMC?
>
> Sent from my iPhone
>

**Comment by clabinsky** [comment]
OMG - it works!

I was just too dumb to install your plugin the right way. Sorry for
wasting your time!

Am 03.01.2017 um 19:59 schrieb Scott James Remnant:
> Do you have the log from EDMC?
>
> Sent from my iPhone
>
