### ISSUE TITLE
Doesn't seem to actually update

### ISSUE THREAD

**Issue by jacaseyclyde** [keybuk/EDMC-Inara#2]
Like the title says, none of the info on INARA seems to be actually updating as a result of this (not sure exactly what all info should be, but I'm assuming at least location should update). I'm logged in fine, with INARA ranking showing. Default EDMC services updating fine as well, using EDMC 2.26, and the current master branch of this, and python 3.6.0

**Comment by keybuk** [comment]
All the plugin does currently is show your Inara Rank.

Inara itself seems pretty abandoned, and Artie hasn’t responded to any of my emails, so turning on the rest hasn’t happened yet.

Scott

**Comment by jacaseyclyde** [comment]
Gotcha, my misunderstanding then.  That's too bad to learn inara is basically dead. I'm realativley new, and looking for tools, and liked the credit goal tracking/prediction. I'll go ahead and close this out though, thanks.
